[package]
name = "tendermint-abci"
version = "0.17.0-rc3"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
server = []
with-tokio = [ "tokio", "tokio-util" ]

[dependencies]
async-trait = "0.1"
bytes = "0.6"
eyre = "0.6"
futures = "0.3"
log = "0.4"
tendermint = { version = "0.17.0-rc3", path = "../tendermint" }
tendermint-proto = { version = "0.17.0-rc3", path = "../proto" }
thiserror = "1.0"

tokio = { version = "0.3", features = [ "macros", "net", "rt", "sync" ], optional = true }
tokio-util = { version = "0.5", features = [ "codec" ], optional = true }
