[package]
name = "tendermint-abci"
version = "0.17.1"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"
description = """
    tendermint-abci provides a framework for building Tendermint applications
    in Rust.
    """

[features]
async = [ "async-trait", "futures", "pin-project" ]
client = []
echo-app = []
runtime-async-std = [ "async-channel", "async-std" ]
runtime-std = []
runtime-tokio = [ "tokio", "tokio-util" ]

[dependencies]
bytes = "1.0"
eyre = "0.6"
log = "0.4"
tendermint = { version = "0.17.1", path = "../tendermint" }
tendermint-proto = { version = "0.17.1", path = "../proto" }
thiserror = "1.0"

async-trait = { version = "0.1", optional = true }
async-channel = { version = "1.5", optional = true }
async-std = { version = "1.8", features = [ "attributes" ], optional = true }
futures = { version = "0.3", optional = true }
pin-project = { version = "1.0", optional = true }
tokio = { version = "1.0", features = [ "macros", "net", "rt", "sync" ], optional = true }
tokio-util = { version = "0.6", features = [ "codec" ], optional = true }
