[workspace]
members = [
    "abci",
    "light-client",
    "light-client-js",
    "p2p",
    "pbt-gen",
    "proto",
    "rpc",
    "std-ext",
    "tendermint",
    "test",
    "testgen"
]
exclude = [
    "proto-compiler"
]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.release]
incremental = true
debug = 0 # Set this to 1 or 2 to get more useful backtraces in debugger.

[profile.release.package.tendermint-light-client-js]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
