[package]
name = "ws-inspect"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.15"
tendermint-rpc = { path = "../../rpc", features = ["websocket-client"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
