# TODO(shonfeder): remove duplication once GitHub addresses one of these
#  - https://github.community/t/support-for-yaml-anchors/16128/15
#  - https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/13
#  - https://github.community/t/using-matrix-variable-in-docker-image-name/17296

name: TEST
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-Dwarnings -Drust-2018-idioms -Wunreachable-pub -Wrust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10

jobs:
  cleanup-runs:
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  crate:
    strategy:
      fail-fast: false
      matrix:
        crate: [tendermint-abci, tendermint, tendermint-light-client, tendermint-proto, tendermint-rpc, tendermint-test, tendermint-testgen]
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, nightly]

    name: ${{ matrix.crate }} on ${{ matrix.os }} with ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/${{ matrix.toolchain }}-*
            ~/.rustup/update-hashes/${{ matrix.toolchain }}-*
          key: rust-toolchain_${{ matrix.os }}-${{ matrix.toolchain }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: cargo, rust-src
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run ${{ matrix.crate }} crate tests
        run: cargo test --all-features --all-targets --no-fail-fast -p ${{ matrix.crate }}

  default:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, nightly]

    name: Default features on ${{ matrix.os }} with ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/${{ matrix.toolchain }}-*
            ~/.rustup/update-hashes/${{ matrix.toolchain }}-*
          key: rust-toolchain_${{ matrix.os }}-${{ matrix.toolchain }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: cargo, rust-src
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run tests with default features
        run: cargo test --all-features --all-targets --no-fail-fast -p ${{ matrix.crate }}

  kvstore:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, nightly]
    services:
      tendermint:
        image: informaldev/tendermint:0.34.13
        ports:
          - 26656:26656
          - 26657:26657
          - 26660:26660

    name: kvstore on ${{ matrix.os }} with ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/${{ matrix.toolchain }}-*
            ~/.rustup/update-hashes/${{ matrix.toolchain }}-*
          key: rust-toolchain_${{ matrix.os }}-${{ matrix.toolchain }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: cargo, rust-src
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run kvstore tests
        env:
          RUST_LOG: debug
        run: cargo test --all-features --all-targets --no-fail-fast --manifest-path tools/kvstore-test/Cargo.toml -- --nocapture

  # From https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/continuous-integration.html#github-actions
  tendermint-light-client-js:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, nightly]

    name: tendermint-light-client-js on ${{ matrix.os }} with ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache toolchain
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/${{ matrix.toolchain }}-*
            ~/.rustup/update-hashes/${{ matrix.toolchain }}-*
          key: rust-toolchain_${{ matrix.os }}-${{ matrix.toolchain }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run headless tests
        run: |
          wasm-pack test --headless --chrome ./light-client-js/
          wasm-pack test --headless --firefox ./light-client-js/
