name: Test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  # TODO(shonfeder): remove duplication once GitHub addresses one of these
  #  - https://github.community/t/support-for-yaml-anchors/16128/15
  #  - https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/13
  #  - https://github.community/t/using-matrix-variable-in-docker-image-name/17296
  tendermint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint
  tendermint-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-rpc
  tendermint-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-proto
  tendermint-light-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-light-client
  tendermint-light-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-light-node
  tendermint-testgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-testgen

  kvstore-integration-stable:
    runs-on: ubuntu-latest
    services:
      tendermint:
        image: informaldev/tendermint:0.34.0
        ports:
          - 26656:26656
          - 26657:26657
          - 26660:26660
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: --manifest-path tools/kvstore-test/Cargo.toml

  kvstore-integration-latest:
    runs-on: ubuntu-latest
    services:
      tendermint:
        image: tendermint/tendermint:latest
        ports:
          - 26656:26656
          - 26657:26657
          - 26660:26660
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        # Don't fail CI due to integration failures on unstable/unreleased versions
        continue-on-error: true
        with:
          command: test-all-features
          args: --manifest-path tools/kvstore-test/Cargo.toml

  nightly-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch the whole Git history for Codecov to find base commit
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - name: Install grcov
        run: if [[ ! -e ~/.cargo/bin/grcov ]]; then cargo install grcov; fi
      - name: Run tests
        run: cargo test
        env:
          RUSTFLAGS: '-Zinstrument-coverage'
      - name: Run grcov
        run: grcov . --binary-path ./target/debug -s . -t lcov --branch --ignore-not-existing -o coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          fail_ci_if_error: true
